name: Publish Docker image

on:
  pull_request:
    branches:
      - '**'
env:
  REGISTRY: 'harbor.status.im'
  PROJECT: 'acid-info/strapi'
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: 'Dockerfile'
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.PROJECT }}:${{ env.BRANCH_NAME }}

